PACKAGE_NAME="mbp13-2-brcmfmac"
PACKAGE_VERSION="7.2.5.1"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build CONFIG_BRCMUTIL= CONFIG_BRCMSMAC= modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
BUILT_MODULE_NAME[0]="brcmfmac"
BUILT_MODULE_LOCATION[0]="brcmfmac"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_ARCH="^x86_64$"
